### ISSUE TITLE
Lambda Runtime

### ISSUE THREAD

**Issue by reziakk** [aws-samples/amazon-connect-global-resiliency#18]
I have the following error:
[Error at /ConnectGlobalResiliencyAdminFrontend/FrontendS3DeploymentStack/Custom::CDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C/Resource] AwsSolutions-L1: The non-container Lambda function is not configured to use the latest runtime version.
Use the latest available runtime for the targeted language to avoid technical debt. Runtimes specific to a language or framework version are deprecated when the version reaches end of life. This rule only applies to non-container Lambda functions.

Already changed the runtime for nodejs to 18.x and the python runtime to 3.11, but I couldn't find the specific runtime for this stack to change.

Any suggestion?

**Comment by virtualgill** [comment]
You can comment out the code that runs these checks in [cdk-stacks.ts](https://github.com/aws-samples/amazon-connect-global-resiliency/blob/main/cdk-stacks/bin/cdk-stacks.ts). 
`Aspects.of(app).add(new AwsSolutionsChecks({ verbose: true }))  //Comment this line to bypass cdk-nag`

The [cdk-nag](https://github.com/cdklabs/cdk-nag) checks represent best practices, but the code will function without the checks running. They can also be suppressed at a granular level as they are broad stroke and there are individual reasons why certain ones are not applicable based on the context.

The code will be updated over time, but the checks can sometimes get updated out of sync with the code.
